### ISSUE TITLE
Running Feature or Scenario Issue

### ISSUE THREAD

**Issue by Kwabs5** [abhinaba-ghosh/cucumber-quick#3]
I'm facing an issue when running the any feature or scenarios using the webdriverio cucumber framework. 

Im seeing the following error message displayed every time I right click and run the .feature file.

2020-06-01T12:57:54.683Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-06-01T12:57:54.685Z ERROR @wdio/cli:launcher: Missing capabilities, exiting with failure
2020-06-01T12:57:54.686Z INFO @wdio/cli:launcher: Run onComplete hook

I do not have anything contained within this hook so i know that is the problem. However what shall I place in that hook?

Any help would be greatly appreciated.

**Comment by abhinaba-ghosh** [comment]
Hi @Kwabs5 ,
Sorry for replying late. I guess, you need to correctly set the ```cucumber-quick``` configuration in your ```.vscode/settings.json``` file.

I have created a video to show the ```webdriverio-cucumber-quick``` execution. Go-through it, and let me know what the configuration you are using.


[cucumber-quick.webm.zip](https://github.com/abhinaba-ghosh/cucumber-quick/files/4728370/cucumber-quick.webm.zip)

**Comment by Kwabs5** [comment]
Hi @abhinaba-ghosh 

Firstly thank you very much for getting back to me, this greatly appreciated. 

Also thank you for providing the video that was very kind of you. With your support
I have now managed to get the the plugin working. 

Thank you once again.

**Comment by abhinaba-ghosh** [comment]
Hi @Kwabs5 , I am glad that it helped. Do raise requests if you like to see some changes/enhancements in the extension.

**Comment by Kwabs5** [comment]
Hi @abhinaba-ghosh ,

Sure I will do, I have seen one small change that is required. When running cucumber scenario outlines the plugin does not seem to run just that scenario outline but all files. I think it would be a good step to have this added in. I will raise a request for this.

Thanks
